### ISSUE TITLE
Custom work item color mismatch

### ISSUE THREAD

**Issue by jdshkolnik** [mohitbagra/vsts-extensions-related-wits#1]
The list of related work items aren't using the colors as defined in the work item definition.

![image](https://cloud.githubusercontent.com/assets/2047520/24811758/652a3984-1b95-11e7-85d0-e6e745ba0248.png)

**Comment by mohitbagra** [comment]
Right now VSTS doesnt provide any rest API to get work item type color data (as far as I know). So I am using hardcoded colors. I am working on revamping the UI for the view, so I'll check if the rest API are provided now. If so, I'll start using that

**Comment by mohitbagra** [comment]
I just updated the extension which uses latest rest API to load the correct work item colors. But this API is probably only there in TFS 2017 update 1.

**Comment by jdshkolnik** [comment]
I don't know which changes it's related to but the content I used as my example above no longer loads anything at all. Oh, and the "i" in "Related Work items" should be capitalized in the tab name.
